import numpy as np 
from scipy.interpolate import CubicSpline, RegularGridInterpolator
import analysis.constants as pc 
from abc import ABC, abstractmethod
from eos.units_system import unit_system, GEOM_UNIT_SYSTEM, COMPOSE_UNIT_SYSTEM, CGS_UNIT_SYSTEM
from scipy.optimize import brentq
from copy import deepcopy

import h5py 


compose_table_thermo_map = {
    "logpress": 1,
    "entropy": 2,
    "mu_n": 3,
    "mu_p": 4,
    "mu_e": 5,
    "logeps": 7,
    "cs2": 12
}

compose_table_yi_map = {
    "Xn": 10,
    "Xp": 11,
    "Xa": 4002
}



class eos_table():
    '''
    EOS table base class
    '''
    def __init__(self,fname,kind="compose"):
        self.units = GEOM_UNIT_SYSTEM

        self._table_name = fname 
        self._table_kind = kind 

        self.logrho = np.array([0])
        self.logtemp = np.array([0])
        self.ye = np.array([0])

    def readtable(self):
        raise RuntimeError("This method is abstract!")
    
    
    def p_of_rho_T_ye(self,rho,T,ye):
        p_i = RegularGridInterpolator(
            (self.ye,self.logtemp,self.logrho),
            self.table_data["logpress"]
        )
        return np.exp(p_i((ye,np.log(T),np.log(rho))))
    
    def _emit_message(self,msg):
        print(f"[INFO]: {msg}")

    def _emit_warning(self,msg):
        print(f"[WARN]: {msg}")

    def _construct_isothermal_table(self,temperature):
        logT = np.log(temperature)
        lTmin = np.amin(self.logtemp)
        if ( logT < lTmin ):
            self._emit_warning(f"Requested temperature {temperature} less than table minimum")
            logT = lTmin 

        # Find the closest available temperature 
        it = np.argmin(np.abs(self.logtemp - logT))
        self._emit_message(f"Closest available temperature ({np.exp(self.logtemp[it])}) will be used)")
        # First find the ye at beta equilibrium 
        mu_e_2d = self.table_data["mu_e"][:, it, :]
        mu_p_2d = self.table_data["mu_p"][:, it, :]
        mu_n_2d = self.table_data["mu_n"][:, it, :]

        grid2d = (self.ye,self.logrho)

        mue_i = RegularGridInterpolator(grid2d, mu_e_2d)
        mup_i = RegularGridInterpolator(grid2d, mu_p_2d)
        mun_i = RegularGridInterpolator(grid2d, mu_n_2d)

        ye_eq = np.zeros_like(self.logrho)
        ye_guess = 0.45 
        for i, lr in enumerate(self.logrho):

            def f(ye):
                pt = np.array([[ye,lr]])
                return (
                    mue_i(pt)[0]
                    + mup_i(pt)[0]
                    - mun_i(pt)[0]
                )

            a = max(self.ye[0], ye_guess - 0.05)
            b = min(self.ye[-1], ye_guess + 0.05)

            try:
                ye_sol = brentq(f, a, b)
            except ValueError:
                ye_sol = brentq(f, self.ye[0], self.ye[-1])

            ye_eq[i] = ye_sol
            ye_guess = ye_sol

        def interp_ye_slice(var_2d, ye_grid, ye_target):
            """
            var_2d: shape (Nr, Ny)
            ye_grid: shape (Ny,)
            ye_target: shape (Nr,)
            """
            Nr = var_2d.shape[1]
            out = np.empty(Nr)

            for i in range(Nr):
                out[i] = np.interp(ye_target[i], ye_grid, var_2d[:,i])

            return out

        iso_table = {} 

        for name, tab in self.table_data.items():
            tab_2d = tab[:,it,:]

            iso_table[name] = interp_ye_slice(tab_2d, self.ye, ye_eq)

        iso_table["energy_shift"] = self.energy_shift 
        
        iso_table["ye"] = ye_eq 
        iso_table["logtemp"] = np.full_like(self.logrho, self.logtemp[it])
        iso_table["logrho"] = self.logrho 
        return iso_table

    def _resample(self, cold_table, npoints):
        lrho0 = cold_table["logrho"][0]
        lrho1 = cold_table["logrho"][-1]
        lrho_new = np.linspace(lrho0, lrho1, npoints)

        def interp_table_entry(lrho, ivar):
            var_i = CubicSpline(cold_table["logrho"], cold_table[ivar])
            return var_i(lrho)
        new_table = {"logrho": lrho_new}

        for var in cold_table.keys():
            if var == "logrho": continue 
            new_table[var] = interp_table_entry(lrho_new, var)
        return new_table 
    
    def _export_grace_table(self, filename, cold_table):
        grace_tab_order = ["logrho", "logtemp", "ye", "logpress", "logeps", "cs2", "entropy"]
        arr = np.column_stack([cold_table[k] for k in grace_tab_order])
        header = f"Slice generated by GRACEpy from compose table {self._table_name}, baryon mass {self.baryon_mass} energy shift {self.energy_shift}. Next line contains number of data points\n{len(cold_table['logrho'])}"
        np.savetxt(
            filename,
            arr,
            header=header,
            comments=''
        )

    def _export_lorene_table(self, filename, table):
        units_lorene = CGS_UNIT_SYSTEM
        uconv = self.units / units_lorene 
        fm_SI   = 1e-15
        mbar_si = pc.mn_MeV * pc.MeV_to_kg
        rho_lorene = np.exp(table["logrho"]) / mbar_si * fm_SI**3 * self.units.dens
        eps_phys = np.exp(table["logeps"]) - table["energy_shift"]
        e_lorene = np.exp(table["logrho"]) * (1+eps_phys) * uconv.dens
        p_lorene = np.exp(table["logpress"]) * uconv.pressure 
        with open(filename, 'w') as f:
            f.write("#\n#\n#\n#\n#\n%d\n#\n#\n#\n" % len(rho_lorene))
            for i,bnd,tmd,p in zip(range(len(rho_lorene)), rho_lorene, e_lorene, p_lorene):
                f.write("%d  %.15e  %.15e  %.15e \n" % (i, bnd, tmd, p))
    
    def _remove_photon_pressure(self, tab):
        uconv = CGS_UNIT_SYSTEM / GEOM_UNIT_SYSTEM

        # T is stored as kB*T in MeV; convert to Kelvin for Stefan-Boltzmann
        T_K = np.exp(tab["logtemp"]) / pc.k_cgs * pc.MeV_to_erg  # [K]

        press_photon_cgs = (1.0 / 3.0) * pc.rad_cgs * T_K**4      # [dyn/cm²]
        press_photon     = press_photon_cgs * uconv.pressure        # [geom]
        e_photon         = 3.0 * press_photon                       # [geom]

        P_tab = np.exp(tab["logpress"])
        e_tab = np.exp(tab["loge"])

        # Guard: photon contribution must be sub-dominant
        bad_P = press_photon >= P_tab
        bad_e = e_photon    >= e_tab
        if np.any(bad_P) or np.any(bad_e):
            self._emit_warning(
                f"Photon pressure >= total pressure at "
                f"{bad_P.sum()} points — clamping to avoid log(<=0)"
            )
            press_photon = np.minimum(press_photon, P_tab * (1.0 - 1e-10))
            e_photon     = np.minimum(e_photon,     e_tab * (1.0 - 1e-10))

        tab["logpress"] = np.log(P_tab - press_photon)
        tab["loge"]     = np.log(e_tab - e_photon)
        return tab


    def _extend_isothermal_low_density(self, cold_table, rho_min, npoints):

        rho = np.exp(cold_table["logrho"])
        p   = np.exp(cold_table["logpress"])
        eps   = np.exp(cold_table["logeps"]) - cold_table["energy_shift"]


        rho0 = rho[0]
        p0   = p[0]
        eps0 = eps[0]

        # Polytrope parameters matched at the table's lower boundary
        gamma_poly   = 4.0 / 3.0
        kappa_poly   = p0 / rho0**gamma_poly
        # eps at junction according to polytrope: P = (gamma-1)*rho*eps_poly
        eps_poly0    = p0 / ((gamma_poly - 1.0) * rho0)
        # Shift to make eps continuous at rho0 (applied ONLY to the poly branch below)
        delta_eps    = eps_poly0 - eps0

        self._emit_message(f"Polytrope: gamma={gamma_poly}  K={kappa_poly:.6g}")
        self._emit_message(f"Junction eps shift delta_eps={delta_eps:.4g}  "
                        f"(rel: {delta_eps/(1e-25 + eps0):.4g})")

        # Build merged density grid
        lrho_new = np.linspace(np.log(rho_min), cold_table["logrho"][-1], npoints)

        def interp_table_entry(lrho, key):
            spl = CubicSpline(cold_table["logrho"], cold_table[key])
            return spl(lrho)

        poly_mask = lrho_new <  cold_table["logrho"][0]
        tab_mask  = lrho_new >= cold_table["logrho"][0]
        poly_lrho = lrho_new[poly_mask]
        tab_lrho  = lrho_new[tab_mask]

        new_table = {}
        new_table["logrho"] = lrho_new
        new_table["energy_shift"] = cold_table["energy_shift"]
        # Temperature and Ye
        new_table["logtemp"] = np.full_like(lrho_new, cold_table["logtemp"][0])
        new_table["ye"]      = np.zeros_like(lrho_new)
        new_table["ye"][poly_mask] = cold_table["ye"][0]
        new_table["ye"][tab_mask]  = interp_table_entry(tab_lrho, "ye")

        # Pressure
        new_table["logpress"] = np.zeros_like(lrho_new)
        poly_rho = np.exp(poly_lrho)
        p_poly   = kappa_poly * poly_rho**gamma_poly
        new_table["logpress"][poly_mask] = np.log(p_poly)
        new_table["logpress"][tab_mask]  = interp_table_entry(tab_lrho, "logpress")

        # Energy density  — delta_eps shift applied ONLY to the polytropic branch
        new_table["logeps"] = np.zeros_like(lrho_new)
        eps_poly = kappa_poly * poly_rho**(gamma_poly - 1.0) / (gamma_poly - 1.0) + delta_eps
        new_table["logeps"][poly_mask] = np.log(eps_poly+new_table["energy_shift"])
        new_table["logeps"][tab_mask]  = interp_table_entry(tab_lrho, "logeps")

        # Entropy
        new_table["entropy"] = np.zeros_like(lrho_new)
        new_table["entropy"][poly_mask] = 0.0
        new_table["entropy"][tab_mask]  = interp_table_entry(tab_lrho, "entropy")

        # Sound speed squared  cs² = gamma*P / (e + P)  (relativistic polytrope)
        new_table["cs2"] = np.zeros_like(lrho_new)
        e_poly_full      = poly_rho * (1.0 + eps_poly)
        new_table["cs2"][poly_mask] = gamma_poly * p_poly / (e_poly_full + p_poly)
        new_table["cs2"][tab_mask]  = interp_table_entry(tab_lrho, "cs2")
        new_table["cs2"] = np.clip(new_table["cs2"], 0.0, 1.0 - 1e-10)

        return new_table
    
    def export_cold_table(self,filename,tab_format="GRACE", resample=-1, temperature=1.0e-15,attach_polytrope=False, remove_radiation=False):

        table = self._construct_isothermal_table(temperature)
        if remove_radiation:
            table = self._remove_photon_pressure(table)
        if attach_polytrope:
            table = self._extend_isothermal_low_density(table,1e-18,50 + len(table["logrho"]))

        if resample>0: 
            table = self._resample(table,resample)
        
        if tab_format=="GRACE":
            self._export_grace_table(filename,table)
        elif tab_format == "LORENE":
            self._export_lorene_table(filename,table)
        else:
            raise ValueError(f"Unknown requested table format {tab_format}")




class scollapse_eos_table(eos_table):
    '''
    Explicit implementation of stellarcollapse table reader.
    Converts the HDF5 table into the GRACE format (units, conventions)
    '''

    def __init__(self,fname):
        super().__init__(fname, "stellarcollapse")
        self.units = GEOM_UNIT_SYSTEM 
        self.readtable() 

    def readtable(self):
        with h5py.File(self._table_name, "r") as f:
            table_data = {}
            for group in f.keys():
                if type(group) == dict:
                    table_data[group] = {}
                    for key in f[group].keys():
                        table_data[group][key] = f[group][key][()]
                else:
                    table_data[group] = f[group][()]
        
        table_units = CGS_UNIT_SYSTEM
        uconv = table_units / self.units 

        self.logrho  = table_data["logrho"] * np.log(10) + np.log(uconv.dens)
        self.logtemp = table_data["logtemp"] * np.log(10)
        self.ye      = table_data["ye"]

        self.table_data = {} 

        self.table_data["mu_e"] = table_data["mu_e"]
        self.table_data["mu_p"] = table_data["mu_p"]
        self.table_data["mu_n"] = table_data["mu_n"]

        self.table_data["Xa"] = table_data["Xa"]
        self.table_data["Xh"] = table_data["Xh"]
        self.table_data["Xn"] = table_data["Xn"]
        self.table_data["Xp"] = table_data["Xp"]

        self.table_data["Abar"] = table_data["Abar"]
        self.table_data["Zbar"] = table_data["Zbar"]

        self.table_data["logpress"] = table_data["logpress"]  * np.log(10) + np.log(uconv.pressure)
        self.table_data["logeps"]   = table_data["logenergy"] * np.log(10) + np.log(uconv.velocity**2)
        self.table_data["entropy"]  = table_data["entropy"]

        self.table_data["cs2"]  = table_data["cs2"] * uconv.velocity**2 

        self.energy_shift = table_data["energy_shift"] * uconv.velocity**2 

        try: self.baryon_mass = table_data["mass_factor"] * uconv.mass 
        except: 
            self._emit_warning("Could not retrieve baryon mass from table, using neutron mass")
            self.baryon_mass = pc.mn_MeV * pc.MeV_to_kg / self.units.mass 


class compose_eos_table(eos_table):
    '''
    Explicit implementation of CompOSE table reader.
    Converts the HDF5 table into the GRACE format (units, conventions)
    '''

    def __init__(self,fname):
        super().__init__(fname,"compose")
        self.units = GEOM_UNIT_SYSTEM
        self.readtable() 

    def readtable(self):
        with h5py.File(self._table_name, "r") as f:
            table_data = {}
            for group in f.keys():
                table_data[group] = {}
                for key in f[group].keys():
                    table_data[group][key] = f[group][key][()]
        # We convert from:
        table_units = COMPOSE_UNIT_SYSTEM
        uconv = table_units / self.units 


        par_data = table_data["Parameters"]
        # First: extract baryon number density,
        # convert to rest mass density using our 
        # unit for the baryon mass 
        self.logrho = np.log(par_data["nb"] * pc.mn_MeV * uconv.dens)

        # Temperature we keep in MeV but we log 
        self.logtemp = np.log(par_data["t"])

        # Ye 
        self.ye = par_data["yq"]

        # Now we read the rest of the table, starting 
        # thermo qties 
        tab_therm_group = table_data["Thermo_qty"]
        tab_therm_data  = tab_therm_group["thermo"]
        tab_therm_idx   = tab_therm_group["index_thermo"]

        self.table_data = {}

        def read_data_entry(name, tab_data, tab_idx, map=compose_table_thermo_map):
            idx_target = map[name]
            for i, idx in enumerate(tab_idx):
                if idx == idx_target:
                    self.table_data[name] = tab_data[i, :, :, :]
                    return
            raise ValueError(f"In compose table {self._table_name}: Missing data for {name}.")
        
        read_data_entry("logpress", tab_therm_data, tab_therm_idx)
        read_data_entry("logeps", tab_therm_data, tab_therm_idx)
        read_data_entry("entropy", tab_therm_data, tab_therm_idx)
        read_data_entry("cs2", tab_therm_data, tab_therm_idx)
        read_data_entry("mu_e", tab_therm_data, tab_therm_idx)
        read_data_entry("mu_n", tab_therm_data, tab_therm_idx)
        read_data_entry("mu_p", tab_therm_data, tab_therm_idx)

        # Convert units 

        # 1 pressure 
        self.table_data["logpress"] = np.log(self.table_data["logpress"] * uconv.pressure)

        # Find energy shift 
        epsmin = np.amin(self.table_data["logeps"]) 
        if epsmin < 0:
            self.energy_shift = -2 * epsmin 
        else:
            self.energy_shift = 0.0 

        # Store log(eps + shift)
        self.table_data["logeps"] = np.log(
            self.table_data["logeps"] + self.energy_shift
        )
        

        # 3 sound speed: sanitize
        cs2_neg_mask = self.table_data["cs2"] <  0 
        cs2_unp_mask = self.table_data["cs2"] >= 1
        self.table_data["cs2"][cs2_neg_mask] = 0.0 
        self.table_data["cs2"][cs2_unp_mask] = 1.0 - 1e-10 

        # 4 Chemical potentials 
        mu_q = deepcopy(self.table_data["mu_p"])
        mu_b = deepcopy(self.table_data["mu_n"])
        mu_e = deepcopy(self.table_data["mu_e"])

        self.table_data["mu_e"] = mu_e - mu_q 
        self.table_data["mu_p"] = mu_q + mu_b 

        # Now read composition pairs 
        yi_tab_data = table_data["Composition_pairs"]["yi"]
        yi_tab_idx  = table_data["Composition_pairs"]["index_yi"]

        read_data_entry("Xn", yi_tab_data, yi_tab_idx, compose_table_yi_map)
        read_data_entry("Xp", yi_tab_data, yi_tab_idx, compose_table_yi_map)
        read_data_entry("Xa", yi_tab_data, yi_tab_idx, compose_table_yi_map)

        self.table_data["Xa"] *= 4 

        # Quadrupoles 
        quad_tab_data = table_data["Composition_quadrupels"]

        self.table_data["Abar"] = quad_tab_data["aav"][0,:,:,:]
        self.table_data["Zbar"] = quad_tab_data["zav"][0,:,:,:]
        self.table_data["Xh"]   = quad_tab_data["aav"][0,:,:,:] * quad_tab_data["yav"][0,:,:,:]

        self.baryon_mass = pc.mn_MeV * uconv.mass 
    
        
class lorene_table:
    '''
    Utility to ingest LORENE table, contains all the nice quirks 
    of the format and units
    '''
    def __init__(self,fname):

        self.clight = 29979245800.0
        self.rhonuc_cgs = 1.66e+20
        
        i,self.nb,self.e,self.p = np.loadtxt(fname, skiprows=9, unpack=True)

        self.p_of_n = CubicSpline(np.log(self.nb),np.log(self.p), extrapolate=False)
        self.e_of_n = CubicSpline(np.log(self.nb),np.log(self.e), extrapolate=False)

        self.n_of_p = CubicSpline(np.log(self.p),np.log(self.nb), extrapolate=False)
        self.n_of_e = CubicSpline(np.log(self.e),np.log(self.nb), extrapolate=False)

        self.h = np.log( (self.p/self.clight**2 + self.e)/(self.nb * 10 * self.rhonuc_cgs) )
        self.h -= self.h[0]

        self.h_of_n = CubicSpline(np.log(self.nb),self.h)
    
    def h__n(self,n_b):
        return self.h_of_n(np.log(n_b))

    def p__n(self, n_b):
        return np.exp(self.p_of_n(np.log(n_b)))

    def e__n(self, n_b):
        return np.exp(self.e_of_n(np.log(n_b)))
    
    def n__e(self, e):
        return np.exp(self.n_of_e(np.log(e)))
    
    def n__p(self, p):
        return np.exp(self.n_of_p(np.log(p)))