#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./job.out.%j
#SBATCH -e ./job.err.%j
# Initial working directory:
#SBATCH -D @JOBDIR@
# Job name
#SBATCH -J @JOBNAME@
#
#SBATCH --partition=@QUEUE@
#SBATCH --nodes=@N_NODES@
#SBATCH --ntasks-per-node=@TASKS_PER_NODE@  
#SBATCH --cpus-per-task=@CPUS_PER_TASK@
#SBATCH --mem=@MEM@
#SBATCH --mail-type=@MAIL_WHEN@
#SBATCH --mail-user=@USER_MAIL@
#SBATCH --time=@WALLTIME@


cd @JOBDIR@

source /etc/profile
module purge
source @ENV_FILE@

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

# ─────────────────────────────────────────────────────────────────────────────
# ── Launch ───────────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────────────
srun ./grace --grace-parfile @PARAMETER_FILE@